(function(self,$){let news_id=0;let listHider;let holder;let items={};let is_chapter=false;function sendAjax(action,data={},callback){data.action=action;data.skin=dle_skin;ShowLoading();$.ajax({url:dle_root+'engine/mods/favdir/api.php',type:'POST',dataType:'json',data:data,}).done(function(d){callback&&callback(d);}).fail(function(e){DLEalert(e.responseText,dle_info);}).always(function(){HideLoading();});}
self.setItem=item=>{let id=item.dataset.id;items[id]=new Proxy(item,{set:function(obj,prop,value){obj[prop]=value;if(prop=='tabs'){let length=obj.tabs.length;if(length===1){let tab=__favorites__.tabs.find(x=>x.id===obj.tabs[0]);obj.innerHTML=tab?tab.title:'undefined';}else if(length>1){obj.innerHTML=length+' folders';}else{obj.innerHTML='Bookmark';}
obj.innerHTML='<span>'+obj.innerHTML+'</span>';}}});items[id].tabs=item.dataset.tabs?item.dataset.tabs.split(',').map(elem=>parseInt(elem,10)):[];}
function hideList(){$('.bookmark__popup').fadeOut(100,()=>$(this).remove());news_id=0;holder=null;}
$(document).on('click','.bookmark__popup-list__item',function(){event.preventDefault();let item=$(this);let tab_id=parseInt(this.dataset.id);sendAjax('setFavorites',{is_chapter:is_chapter,news_id:news_id,tab_id:tab_id},d=>{$(this).toggleClass('active');$('.bookmark--counter').html(d.count);items[news_id].tabs=d.tabs;typeof favdir==='object'&&favdir.setTabCounter(tab_id,d.tab_count);})}).on('click','.bookmark--trigger',function(){event.preventDefault();event.stopPropagation();if(dle_group==5){DLEalert(__favorites__.guest_error,dle_info);return;}
if(news_id==this.dataset.id){hideList();return;}
clearTimeout(listHider);news_id=parseInt(this.dataset.id);is_chapter=this.dataset.hasOwnProperty('chapter');$('.bookmark__popup').remove();let popup=document.createElement('div');popup.className='bookmark__popup';let list=document.createElement('div');list.className='bookmark__popup-list';$(popup).appendTo($(this).parent());for(let tab of __favorites__.tabs){let item=document.createElement('a');item.className='bookmark__popup-list__item';item.href='#';item.dataset.id=tab.id;item.innerHTML=tab.title;tab.public&&$(item).addClass('public');tab.system_name&&$(item).addClass('system');items[news_id].tabs&&items[news_id].tabs.includes(tab.id)&&$(item).addClass('active');list.appendChild(item);}
popup.appendChild(list);if(this.dataset.note){let note=document.createElement('a');note.className='note__popup-trigger';note.dataset.id=news_id;note.href='#';note.innerHTML=this.dataset.note;popup.appendChild(note);}
$(popup).slideDown(150);}).on('mouseenter','.bookmark__popup, .bookmark--trigger',function(){clearTimeout(listHider);}).on('mouseleave','.bookmark__popup, .bookmark--trigger',function(){listHider=setTimeout(()=>{hideList();},700);}).on('click','body',function(){if($(event.target).closest('.bookmark__popup, .bookmark--trigger').length!=1){hideList();}})
$(function(){$('.bookmark--trigger').each(function(){self.setItem(this);})});})(window.favlist={},jQuery);